### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by moo06** [lexus2k/ssd1306#100]
Hi,
Is there any way I could print a variable onto the OLED?

Thanks

**Comment by lexus2k** [comment]
Hi,

what type of variable you're trying to print?

**Comment by moo06** [comment]
Hi,
It is an analogRead() because I'm debugging the button values so I can make a tech demo. Since I'm using an ATTINY85, and I'm using practically all the pins, I can only try and show it on the screen.

Thanks

**Comment by lexus2k** [comment]
Hi here is an example for printing numbers:

```.cpp
#include "ssd1306.h"
#include <stdio.h>

void printNumber(int x, int y, int number)
{
    char intStr[12];
    snprintf(intStr, sizeof(intStr), "%i", number );
    ssd1306_printFixed (x, y, intStr, STYLE_NORMAL);
}
```

**Comment by lexus2k** [comment]
Did the example above help you?

**Comment by moo06** [comment]
Hi, yes thank you.
