### ISSUE TITLE
Bigger Fonts

### ISSUE THREAD

**Issue by bobybobybob** [lexus2k/ssd1306#11]
#### library version
1.3.1

#### LCD display type
SSD1306 I2C

I like your libary.
Can you integrate bigger Fonts?  And possible to mix small + big fonts in one screen?

**Comment by lexus2k** [comment]
Hello @bobybobybob,

Yes, it is possible. But there are some limitations. What chip do you use in your project?
What font size would you like to work with?
There are several solutions:
1. The simplest is to implement big fonts output function, which stretches existent font from 6x8 to 12x16.
2. Add new functions and new fonts 12x16. Current 6x8 font requires 1KiB of SRAM. 12x16 font will requires 4KiB of SRAM, and so on.

Could you please, describe your use-case?

**Comment by bobybobybob** [comment]
Hello, 
just some bigger Fonts... excampel for fullscreen Numbers for only single Temperature or Speed etc. or other short information is better to read with bigger fonts than in small. The small font is perfect to fit much information on little Display, but hard to read for old people. 

Maybe it is usefull fonts only with numbers, one with numbers + symbols and one with ABC123°²@+-: etc. so RAM can be low when no need for ABC and only need numbers.

**Comment by lexus2k** [comment]
Ok, understood. How big fonts would you like to have? Is it enough to have twice in size to those, that are currently in the library (12x16)? Or maybe you prefer to have fonts with height 32?

**Comment by lexus2k** [comment]
Hi @bobybobybob ,

Please, check latest sourcess on master branch. I added function to display double font. Is it ok for you?
`ssd1306_charF12x16()`

**Comment by bobybobybob** [comment]
Very Cool :-)   I install 1.3.1 and IDE say  exit status 1
'ssd1306_charF12x16' was not declared in this scope

**Comment by lexus2k** [comment]
Yes, I didn't release next version after 1.3.1.
That's why I asked you to check lastest master sources and let me know if new function is ok for you.

**Comment by bobybobybob** [comment]
I have to deleate ssd1306 folder in libary folder and reinstall it. Now it works. Very great. Thank you very much!!!

**Comment by lexus2k** [comment]
ok, thank you.
I'm closing this issue. Let me know if you need anything else.
