### ISSUE TITLE
Add support for building as component under ESP-IDF v4.x 

### ISSUE THREAD

**Issue by danak6jq** [lexus2k/ssd1306#115]
ESP-IDF v4.x defaults to cmake builds, and with that adds a requirement for a CMakeLists.txt file at the time top-level (similar to component.mk for ESP-IDF v3.x).

(Opening issue to track PR #114 )

**Comment by lexus2k** [comment]
Hello,

it is critical for you to use ssd1306 libray. Can you try [lcdgfx](https://github.com/lexus2k/lcdgfx)?

**Comment by danak6jq** [comment]
I'd already started a project with the ssd1306 library out of habit, and I'm happy to report that it does just work under ESP-IDF v4.x now - thank you.

I also tested lcdgfx and - it just works on ESP-IDF. I'll use that on future projects.

Thank you very much for the very useful project.
