### ISSUE TITLE
lcd_common.c:100:17: error: Uninitialized variable: args [uninitvar]

### ISSUE THREAD

**Issue by Harvie** [lexus2k/ssd1306#117]
Hello,
i've "accidentaly" checked the ssd1306 using cppcheck static analyzer and it seems quite ok, only one tiny error was found:

```
$ cppcheck --force . >/dev/null
src/lcd/lcd_common.c:100:17: error: Uninitialized variable: args [uninitvar]
            if (args < 0)
                ^
```

**Comment by lexus2k** [comment]
Hi @Harvie 

Thank you for the finding, but my cppcheck doesn't show any warning.
I fixed this error (you can see commit in this issue).

Best regards

**Comment by Harvie** [comment]
> Thank you for the finding, but my cppcheck doesn't show any warning.

i've just checked 1.8_dev branch and the warning has disappeared.

For the reference:

```
$ cppcheck --version
Cppcheck 2.2
```

**Comment by lexus2k** [comment]
@Harvie 

Thank you very much.
