### ISSUE TITLE
SSD1306 64*48

### ISSUE THREAD

**Issue by coelner** [lexus2k/ssd1306#120]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The same usage like the other screen sizes

**Describe alternatives you've considered**
There is a branch in the Adafruit SSD1306 library (https://github.com/mcauser/Adafruit_SSD1306/tree/esp8266-64x48)

**Additional context**
This is the display which I want to use: https://docs.wemos.cc/en/latest/d1_mini_shield/oled_0_66.html

**Comment by lexus2k** [comment]
Hi @coelner 

Can you run ssd1306_demo and capture what it displays for me?

**Comment by coelner** [comment]
Sorry, my v2.0.0 board went up in smoke. Unfortunately I have no replacement for this

**Comment by lexus2k** [comment]
@coelner  Anyway, let me know, if you still need 64x48 or 64x32 display support.

**Comment by coelner** [comment]
Yes, the 64x48 size would be nice.

**Comment by lexus2k** [comment]
If it is suitable for you, ssd1306 is supported by [lcdgfx](https://github.com/lexus2k/lcdgfx) library. That is improved version of this library
