### ISSUE TITLE
negativemode for canvas printfixed

### ISSUE THREAD

**Issue by alijani1** [lexus2k/ssd1306#125]
Not able to print text on an existing canvas in negative mode.  Need SSD1306_negativemode() equivalent for a canvas.

I understand we can invert a whole canvas but one should be able to print invented text on a small part of an existing canvas.

**Comment by lexus2k** [comment]
Hello, I will check what can be done in your case.
If your project is not strongly tied to this library, please check another my library [lcdgfx](https://github.com/lexus2k/lcdgfx).
It supports `invertColor()` method both for canvas and display,
Let me know, what you think.
