### ISSUE TITLE
How to use with I2c?

### ISSUE THREAD

**Issue by EasyG0ing1** [lexus2k/ssd1306#130]
Ask any question, you have, regarding the library
I couldn't find any examples, nor anything in the documentation about how to use this with an sssd1306 over I2c. Docs say "I2C support via Wire" - but that means nothing to me ... 

Can you update your docs at least and show how to us I2C with this library?\

Thanks

**Comment by lexus2k** [comment]
Hi Michael.

Please, refer to the [examples](https://github.com/lexus2k/ssd1306/blob/master/examples/demos/ssd1306_demo/ssd1306_demo.ino): by default ssd1306 demo uses i2c.
Please, find the information in the [documentation](https://lexus2k.github.io/ssd1306/group___l_c_d___i_n_t_e_r_f_a_c_e___a_p_i.html#gad4cf492be6e9c71cd461baf8709ab617)

It is very helpful to point the platform, you're working with.
