### ISSUE TITLE
ssd1306/src/ssd1306_hal/esp/platform.c line 244  should the line    platform_i2c_send(*data)  be  platform_spi_send(*data);

### ISSUE THREAD

**Issue by SamMcCormick61** [lexus2k/ssd1306#131]
esp/platform.c
line 244
should the line    
platform_i2c_send(*data)  
be 
 platform_spi_send(*data);

static void platform_spi_send_buffer(const uint8_t *data, uint16_t len)
{
    while (len--)
    {
        **platform_i2c_send(*data);**
        data++;
    }
}

**Comment by lexus2k** [comment]
Hi :)
nice catch, the fix is ready on the master branch
