### ISSUE TITLE
SSD1306 Examples fail to compile under esp32 2.0.0 Board

### ISSUE THREAD

**Issue by ericd1949** [lexus2k/ssd1306#132]
I found this when compiling one of my sketches on a Mac with Arduino 1.8.13, not the latest I know. But the code, as described in the error is still there, If I'm wrong - heartfelt apologies.
This did not occur when I downgraded the ESP32 boards to 1.0.6

The ssd1306_demo example sketch also, error given:
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:186:9: error: 'i2s_write_bytes' was not declared in this scope
         i2s_write_bytes(I2S_PORT, (char*)line, (m_ptr - line) * sizeof(uint16_t), portMAX_DELAY);
         ^~~~~~~~~~~~~~~

Also, maybe relevant an earlier error said:
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:119:32: warning: 'I2S_COMM_FORMAT_I2S_MSB' is deprecated [-Wdeprecated-declarations]
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
                                ^~~~~~~~~~~~~~~~~~~~~~~

********* Full Error log **********
warning: 'I2S_COMM_FORMAT_I2S_MSB' is deprecated [-Wdeprecated-declarations]
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
                                ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/tools/sdk/esp32/include/hal/esp32/include/hal/i2s_ll.h:30,
                 from /Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/tools/sdk/esp32/include/hal/include/hal/i2s_hal.h:28,
                 from /Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/tools/sdk/esp32/include/driver/include/driver/i2s.h:16,
                 from /Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.h:12,
                 from /Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:5:
/Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/tools/sdk/esp32/include/hal/include/hal/i2s_types.h:71:5: note: declared here
     I2S_COMM_FORMAT_I2S_MSB   __attribute__((deprecated)) = 0x01, /*!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~~~~~
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp: In member function 'void CompositeOutput::sendFrameHalfResolution(const uint8_t*)':
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:186:9: error: 'i2s_write_bytes' was not declared in this scope
         i2s_write_bytes(I2S_PORT, (char*)line, (m_ptr - line) * sizeof(uint16_t), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:186:9: note: suggested alternative: 'i2s_write_expand'
         i2s_write_bytes(I2S_PORT, (char*)line, (m_ptr - line) * sizeof(uint16_t), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
         i2s_write_expand
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp: In member function 'void CompositeOutput::check_buffer()':
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:278:9: error: 'i2s_write_bytes' was not declared in this scope
         i2s_write_bytes(I2S_PORT, (char*)line, sizeof(uint16_t) * (m_end - line), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
/Users/ericd/Documents/Arduino/libraries/ssd1306/src/intf/vga/esp32/CompositeOutput.cpp:278:9: note: suggested alternative: 'i2s_write_expand'
         i2s_write_bytes(I2S_PORT, (char*)line, sizeof(uint16_t) * (m_end - line), portMAX_DELAY);
         ^~~~~~~~~~~~~~~
         i2s_write_expand
Using library ssd1306 at version 1.8.2 in folder: /Users/ericd/Documents/Arduino/libraries/ssd1306 
Using library Wire at version 2.0.0 in folder: /Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/Wire 
Using library SPI at version 2.0.0 in folder: /Users/ericd/Library/Arduino15/packages/esp32/hardware/esp32/2.0.0/libraries/SPI 
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by lexus2k** [comment]
Hmm, I fixed some similar issue for lcdgfx few days or weeks ago.
It looks like ESP32 IDE was updated greatly.
Can you port the changes from https://github.com/lexus2k/lcdgfx/commit/053e92216829df4e040df8c5f1388b3f0f271dda commit, and let me know if the issue is gone?

**Comment by ericd1949** [comment]
Very happy to do that, I'm away this weekend, so I'll try it early next week.

Just to be clear, I'll put the changes from that commit into nano_gfx_types .h and see what happens

**Comment by ericd1949** [comment]
Yes, excellent, that fixed it.     I changed:

#define min(a,b) ((a)<(b)?(a):(b))         to           #define __min(a,b) ((a)<(b)?(a):(b))
and
#define max(a,b) ((a)>(b)?(a):(b))         to           #define __max(a,b) ((a)>(b)?(a):(b))

Thanks for your help.
