### ISSUE TITLE
GPIO character device instead of sysfs

### ISSUE THREAD

**Issue by sgjava** [lexus2k/ssd1306#134]
Have you looked at https://github.com/vsergeev/c-periphery? sysfs is deprecated and GPIO character device replaces it. I worked on https://github.com/olikraus/u8g2/tree/master/sys/arm-linux using c-periphery and boosted performance of SW and HW I2C and SPI. I also made it thread safe and multiple display capable. I'm looking for a library to write a Java wrapper for that handles color displays like yours.

**Comment by lexus2k** [comment]
Hi, it's nice idea. I will check the peripheral library.

**Comment by sgjava** [comment]
I will look at current Linux implementation.
