### ISSUE TITLE
Small height filled rectangles mask issue

### ISSUE THREAD

**Issue by drgallaci** [lexus2k/ssd1306#18]
When drawing small height filled rectangles with NanoCanvas::fillRect() if y1 and y2 are in the same bank the mask calculated wrong by 
"mask = (mask >> ((y1 & 7) + 7 - (y2 & 7))) << (7 - (y2 & 7));" in line #92 of file nano_gfx.cpp.
The filled rectangle vertical position will be pseudo random depending on y1 and y2.
This behavior applies to only small height (1-7 pixels) objects, and don't apply to >8 pixel height filled rectangles (as y1 and y2 are not in the same bank and mask calculated elsewhere).

Reproducing - see the attached project file (.txt extension)

Because of the last tag of mask based on y2 not y1, when drawing a slightly descending line (from left to right) using fillRect() it can be seen a strange line with random segments.

Fix:
"mask = (mask >> ((y1 & 7) + 7 - (y2 & 7))) << (y1 & 7); "

Library version: 1.4.2
LCD display type: SSD1306 based 128x32 monochrome OLED

[GL_mini_OLED_disp_fix_nanoGFX_fillRect.txt](https://github.com/lexus2k/ssd1306/files/1647817/GL_mini_OLED_disp_fix_nanoGFX_fillRect.txt)

**Comment by lexus2k** [comment]
Hi @drgallaci,
Version 1.4.3 released with your fix. Thank you very much.
