### ISSUE TITLE
NanoCanvas::fillRect x-y inconsistency

### ISSUE THREAD

**Issue by drgallaci** [lexus2k/ssd1306#20]
NanoCanvas::fillRect() x/y size is inconsistent, and also inconsistent with ::drawRect().

Calling c.fillRect(10,10, 13, 13, 0xFF); results in drawing a 3x4 pixel filled rectangle instead of a 4x4 pixel filled square, caused by line #102 in file nano_gfx.cpp (x>x2):
`for (uint8_t x=x1; x<x2; x++)`
Fix:
`for (uint8_t x=x1; x<=x2; x++)`

Library version: 1.4.2
LCD display type: SSD1306 based 128x32 monochrome OLED

**Comment by lexus2k** [comment]
Hi @drgallaci,
Version 1.4.3 released with your fix. Thank you very much.
