### ISSUE TITLE
`%` character flipped

### ISSUE THREAD

**Issue by CromFr** [lexus2k/ssd1306#23]
Not sure if it is intentional, but the default font for rendering the `%` character is fliped left/right (or top/bottom depending on how your brain works ^^)

However the courier_new_font11x16_digits displays the `%` character correctly

## LCD display type
SSD1306

## Steps to reproduce the issue
```c
#include "ssd1306.h"
#include "font6x8.h"
void setup()
{
    ssd1306_128x64_i2c_init();
    ssd1306_fillScreen(0x00);
    ssd1306_setFixedFont(ssd1306xled_font6x8);
    ssd1306_printFixed  (0,  8, "This % isn't right", STYLE_NORMAL);
}
void loop(){}
```

## Actual behavior
![img_20180129_132920](https://user-images.githubusercontent.com/999188/35510583-f120aa5c-04f8-11e8-99d0-86db7f769882.jpg)

**Comment by lexus2k** [comment]
Hi Charles,

Good finding. Fixed in commit, attached to this issue.

**Comment by CromFr** [comment]
Damn you're quick :)
Thanks !

**Comment by lexus2k** [comment]
1.4.7 with the % char fix is released.
