### ISSUE TITLE
flip screen

### ISSUE THREAD

**Issue by Lenticualis** [lexus2k/ssd1306#26]
Perhaps I haven't found the function, but is there any way to flip the screen?

Regards

**Comment by lexus2k** [comment]
Hi,

There is no such function yet. What type of OLED display do you have?

**Comment by Lenticualis** [comment]
Thx for your reply, 
It is a ssd1306 128x32 oled i2c

**Comment by lexus2k** [comment]
Please check latest source on master branch. I added flip functions. Refer to commit 3a6f011

**Comment by lexus2k** [comment]
Online documentation is updated 
https://lexus2k.github.io/ssd1306/group___l_c_d___d_i_s_p_l_a_y___a_p_i.html#gac6a71a50e10fb75181c0c851821d3de6

**Comment by Lenticualis** [comment]
Great!!! Many Thanks
