### ISSUE TITLE
The project

### ISSUE THREAD

**Issue by classic-audio** [lexus2k/ssd1306#44]
I contacted you some time ago and you did change your libraries so also ATtiny84 could be used.
I have now my project ready.
ATtiny84
Program Storage 7202b 87% - Dynamic memory 202b 39%
#include "ssd1306.h"
#include "nano_gfx.h"
Display SSD1306 I2C
Digital ports 6
Analog ports 2

Thank you for your support.

![sc-interface](https://user-images.githubusercontent.com/39434972/43356975-758e81c4-927a-11e8-8739-97b932841440.jpg)

The functionality 
I am making my own audio test equipment and this is a soundcard interface for testing audio specifications.

**Comment by lexus2k** [comment]
Hi Frede,

Thank you for the kind words, you're welcome. Your projects look great, I'm impressed (I checked http://www.classic-quad.dk site).
Let me know if I can add more useful features.

Aleksei.

**Comment by classic-audio** [comment]
Thank you Aleksei, perhaps my site: http://www.beolab.dk also could be of interest for a short visit. 
This site is also in English.
The above testequipment is used every day. It is now the 4.th. generation and is working very well for testing specifications like
Distortion - frequency response - signal/noise - channel separation - ect.
The equipment is "the front end" of a high class soundcard.
Measurements software: TrueRTA and AudioTester.

**Comment by lexus2k** [comment]
Does this site consist of single page?
Do you develop PCB design by yourself for the projects?

**Comment by classic-audio** [comment]
The beolab.dk is several webpages - click Link to......
I delvelop the circuits and the PCB myself - yes.

**Comment by lexus2k** [comment]
Thank you for the points. I've never heard about Beolab trademark before. I've read your history in "my passion" blog, you really do amazing things.
