### ISSUE TITLE
console.print() issues

### ISSUE THREAD

**Issue by gcormier** [lexus2k/ssd1306#51]
## library version
1.7.8
## LCD display type
i2c ssd1306

I can't figure out the console.

```
  console.clear();
  console.print("Temp : ");
  console.println(12);
  console.print("Humidity : ");
  console.println(34);
```
This outputs one line at the top of the screen, "Humidity : 34"

```
  console.clear();
  console.print("Temp : ");
  console.println(12);
  console.print("Humidity : \n");
  console.println(34);
```

This outputs "Humidity : (newline)34" and it scrolls down the screen, looping to the top after a hitting the bottom.

**Comment by lexus2k** [comment]
Hello,

please, provide full sketch code. Maybe the root cause is the font being used. I tested your code and in all cases, I've got exactly what is expected.
![first_lines](https://user-images.githubusercontent.com/16983230/46253208-2b584880-c4b9-11e8-8b98-16b2b7334b4f.gif)

**Comment by gcormier** [comment]
```
void setup()
{
  Serial.begin(9600);
  Serial.println(F("Starting..."));
  pinMode(PIN, INPUT);
#ifdef DEBUG
  pinMode(DEBUGPIN, OUTPUT);
  digitalWrite(DEBUGPIN, LOW);
#endif


  ssd1306_128x64_i2c_init();
  ssd1306_clearScreen(); 
  ssd1306_setFixedFont(ssd1306xled_font6x8);
  console.begin();
 
  while (true)
  {
    updateDisplay();
    delay(250);
  }
}

void updateDisplay()
{
  console.clear();
  
  console.print("Temp : ");
  console.println(12);
  console.print("Humidity : \n");
  console.println(34);
  
}
```

This prints 

> Humidity : 
> 34

Any it scrolls downwards looping around at the top.

**Comment by gcormier** [comment]
Great, thanks!
