### ISSUE TITLE
which ssd1306 library on the Arduino IDE library manager to use?

### ISSUE THREAD

**Issue by dportabella** [lexus2k/ssd1306#54]
I'd like to use the ssd1306 arduino library for my "ESP8266 0.96''OLED ESP-12F WIFI Development Board":
https://www.ebay.es/itm/ESP8266-0-96OLED-ESP-12F-WIFI-Development-Board-CP2102-Micro-USB-18650-Battery/113002221260

Your README.md file says:

> Setting up
>   Setting up for Arduino: (variant 2)
>     Install ssd1306 library via Arduino IDE library manager
> 

there are many ssd1306 libraries on the Arduino IDE library manager.
for instance: Acrobotic SSD1306, Adafruit SSD1306, ESP8266 and ESP32 Oled Driver for SSD1306 display...

Which one of those libraries are compatible?

**Comment by lexus2k** [comment]
Hello,
This github account is dedicated to ssd1306 by Alexey Dynda. See picture below:
![default](https://user-images.githubusercontent.com/16983230/47289808-cdde9400-d63f-11e8-9f23-e87dda7a914f.png)

**Comment by lexus2k** [comment]
This account is dedicated to ssd1306 by Alexey Dynda. See picture below:
![default](https://user-images.githubusercontent.com/16983230/47289931-54937100-d640-11e8-95b0-a5b0ebe7110b.png)

**Comment by dportabella** [comment]
maybe you can add this to the README.md file...

**Comment by lexus2k** [comment]
Added.
