### ISSUE TITLE
Calling ssd1306_setMode on ssd1306_128x32 display will hang the program

### ISSUE THREAD

**Issue by AuthenticOleksiis** [lexus2k/ssd1306#57]
https://github.com/lexus2k/ssd1306/blob/7f8bb7d4f391b27e2b64d6a98d6c15c6bcf48041/src/lcd/oled_ssd1306.c#L233

Has to be 
ssd1306_lcd.set_mode = ssd1306_setMode_int;

**Comment by lexus2k** [comment]
Hello, thank you for the finding.
Your fix is integrated on master branch
