### ISSUE TITLE
Fill

### ISSUE THREAD

**Issue by scargill** [lexus2k/ssd1306#6]
Not QUITE understanding the fill rect function in canvas

  canvas.fillRect(80,20,100,25,1);

That last parameter - I've tried 1, 255, -1  - I cannot fill a rectangle in white on the SSD1306 32 high display...  rectangle and text works just fine

???

**Comment by scargill** [comment]
I'll rephrase that - the function  as called above, if called after I've drawn some text stops all updates - my text updates don't happen. If I comment out that fill, everything works...

**Comment by lexus2k** [comment]
I fixed the issue with fillRect(). Please, check latest sources.

**Comment by lexus2k** [comment]
Let me know if the fix works for you. I checked on Nano with ssd1306 and now filled rectangle looks good.

**Comment by lexus2k** [comment]
Any news on the issue?

**Comment by lexus2k** [comment]
I'm closing the issue. If you still observe the problem in the latest official release, please, reopen the issue
