### ISSUE TITLE
Where is the documentation for this library!? I just want to know how to use it.

### ISSUE THREAD

**Issue by pikipupiba** [lexus2k/ssd1306#67]
It might be because I'm new to git hub but I cannot for the life of me find any actual documentation of how to use this library.

For example, the Display class and what fonts are available to the SetFont member function.

**Comment by lexus2k** [comment]
Hello,

As it is said in main [README.md](https://github.com/lexus2k/ssd1306/blob/master/README.md) file: Doxygen documentation can be found at [github.io](http://lexus2k.github.io/ssd1306) site.
Please, take into account, that main library interface is C, and not C++. This is to reduce memory consumption for small controllers. The library also has some C++ API, allowing to perform powerful graphics operations.

The API, you would like to use (_For example, the Display class._) is in development, and you can check ssd1306_demo in [2.0.0_dev](https://github.com/lexus2k/ssd1306/tree/2.0.0_dev) branch.
To figure out how to use official library releases, please refer to [examples](https://github.com/lexus2k/ssd1306/tree/master/examples)
