### ISSUE TITLE
Text overwriting

### ISSUE THREAD

**Issue by scargill** [lexus2k/ssd1306#7]
I just noticed - that using the Canvas - if you write text.. then overwrite - the black pixels are not restored... ie overwrite an E with an O and the original pixels remain intact..

Which means the only way to update a line--- is to wipe the screen and redraw the lot?

**Comment by lexus2k** [comment]
Hi Peter,
I understand your point. My initial thoughts were to use fill-rectangle or function something like this to clear the area behind the text if needed. To make usage of charF6x8() simpler, I updated the method to restore black pixels.
Please, check latest version on github

**Comment by lexus2k** [comment]
Any news?

**Comment by lexus2k** [comment]
Closed as it fixed in latest release
