### ISSUE TITLE
composite_video.c:139:16: error: 'ssd1306_lcd_t' has no member named 'set_mode'

### ISSUE THREAD

**Issue by aldolo69** [lexus2k/ssd1306#78]
**Describe the bug**

it seem last commit has broken something. my test progs and even demo do not compile anymore due to 
composite_video.c:139:16: error: 'ssd1306_lcd_t' has no member named 'set_mode'

**To Reproduce**

-compile, for example, the ssd1306_demo prog

**Please complete the following information:**
 - library version the very last
 - Platform  arduino uno 
 - arduino 1.8.5

**Comment by lexus2k** [comment]
Thank you for reporting the issue.
Fixed per ae3339c commit.

**Comment by lucasromeiro** [comment]
How I can solve this? Is a balada problem for me

**Comment by lexus2k** [comment]
@lucasromeiro 
What version do you use? Did you install ssd1306 from Arduino IDE manager or manually?

**Comment by lucasromeiro** [comment]
> @lucasromeiro
> What version do you use? Did you install ssd1306 from Arduino IDE manager or manually?
> 
> Can you try 1.7_dev branch or master branch? They should be OK.

To solve I had to go back to version 17 17
I will wait for a new version to update with the fix.
