### ISSUE TITLE
All fonts render garbage

### ISSUE THREAD

**Issue by amyspark** [lexus2k/ssd1306#79]
**Describe the bug**
With current master, all fonts render garbage in my toy clock application. This bug was introduced in 67ffeb4a738e677fb93338ef1373ab4193400411 as per `git bisect` starting from `v1.7.12`; I don't know specifically what causes it.

**To Reproduce**
Upload the following sample to your board of choice (mine is an Arduino Uno, with a ST7735 LCD panel connected):

```c
#include <ssd1306.h>

void setup() {
  st7735_128x160_spi_init(8, 10, 9);
  ssd1306_fillScreen(0x00);
  ssd1306_setFixedFont(comic_sans_font24x32_123);
  ssd1306_printFixed(0, 0, "111", STYLE_NORMAL);
}

void loop()
{

}

```

**Expected behavior**
I wanted to see "asd" in the screen. Instead, I get what is shown in the photo below.

**Screenshots**
<img src="https://user-images.githubusercontent.com/13498015/57234928-22ec6100-6ff8-11e9-9c4e-ff806fa0a3b5.jpg" height="256" />

**Please complete the following information:**
 - library version: ae3339ca4a94835c613f3f42ca342dec6a1a9bb9
 - LCD display type: st7735, 160x128, green tab
 - OS [e.g. linux, windows]: MacOS High Sierra 10.13.6
 - Platform [e.g. Atmega328p, esp32, etc.]: Arduino Uno (Atmega328p)
 - IDE if using some: Arduino 1.8.9, AVR toolchain v1.6.21

**Additional context**
I edited the original description to use supported characters.

**Comment by lexus2k** [comment]
Thank you for reporting. I confirm, the issue exists

**Comment by lexus2k** [comment]
Can you try the following code instead?

```.cpp
#include <ssd1306.h>

void setup() {
  st7735_128x160_spi_init(8, 10, 9);
  ssd1306_fillScreen(0x00);
  ssd1306_setFixedFont(comic_sans_font24x32_123);
  ssd1306_printFixed8(0, 0, "111", STYLE_NORMAL);
}

void loop()
{

}
```

**Comment by amyspark** [comment]
I can confirm this works with `printFixed8`. What's the issue here?

**Comment by lexus2k** [comment]
I reverted last 3 commits. So, now original example from your description should work as is.
The issue was related to the functionality, which I removed from the library. Thank you for reporting, I will think on how to do changes to the library more carefully.
