### ISSUE TITLE
Garbage on screen 

### ISSUE THREAD

**Issue by trollsid** [lexus2k/ssd1306#87]
Test on ssd1351_demo

**Describe the bug**
Garbage on screen after run any command
**To Reproduce**
1. Compile and run
2. See error

**Screenshots**

**Please complete the following information:**
 - library version 2.0_dev
 - LCD display type -ssd1351
 - OS : linux
 - Platform esp32
 - IDE : idf + vim

**Additional context**

**Comment by lexus2k** [comment]
Hello, Dmitry.

Thanks for reporting. I don't have esp32 dev module by hand right now, but you could greatly help me, if you can check 1.7.x version and let me know if it works.

PS. Could you please post here display initialization code from your sketch? Thank you.

**Comment by lexus2k** [comment]
Please,  check latest commit 5dd0328. It fixes spi issue with esp32 idf

**Comment by lexus2k** [comment]
Fixed, feel free to reopen, if you have any issues
