### ISSUE TITLE
Only fonts starting ssd1306xled work

### ISSUE THREAD

**Issue by rickyelqasem** [lexus2k/ssd1306#98]
**Describe the bug**
If choose any other font than the ones starting ssd1306xled I get corruption on the screen. ssd1306xled fonts and digital_font5x7 work fine. Is there something special I need to do?

**To Reproduce**

**Expected behavior**
All fonts work

**Screenshots**

**Please complete the following information:**
 - 1.8.1
 - OLED 128x64
 - Windows
 - Atmega328p
 - PlatformIO

**Additional context**

**Comment by lexus2k** [comment]
Hi @rickyelqasem 

Could you please provide more details? Like sketch code, which doesn't work.
BTW, there are 2 types of fonts, available in the library: Fixed width fonts, and Free type fonts. To set the font, you need to use different functions, depending on selected font type: `ssd1306_setFixedFont` or `ssd1306_setFreeFont`.

**Comment by rickyelqasem** [comment]
Ok thanks.. Is there any more fonts you know of?

**Comment by lexus2k** [comment]
You can create your own fonts for the library. Please, read this instruction: https://github.com/lexus2k/ssd1306/wiki/How-to-create-new-font-for-the-library
